# Generated by Django 6.1.1 on 2026-10-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='Meralco / Local Electric Coop', max_length=150)),
                ('meter_number', models.CharField(max_length=100)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('billing_period', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electricity_bills', to='core.location')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='Maynilad / Local Water District', max_length=150)),
                ('meter_number', models.CharField(max_length=100)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('billing_period', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_bills', to='core.location')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
            },
        ),
    ]
