# Generated by Django 6.1.1 on 2026-10-09 06:10

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbill',
            old_name='bill_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='provider',
            new_name='water_source',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='meter_number',
            new_name='tank',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='previous_reading',
            new_name='initial_level',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='current_reading',
            new_name='subsequent_level',
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='billing_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='subsequent_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='water_encoded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='initial_additional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='initial_checked_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='initial_remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='refilled_gallons',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='subsequent_additional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='subsequent_checked_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='subsequent_remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='waterbill',
            options={'ordering': ['-date', '-id']},
        ),
    ]
