# Generated by Django 6.1.1 on 2026-10-09 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting'),
        ('utilities', '0002_water_monitoring_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='water_source',
            field=models.CharField(default='Unspecified', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='waterbill',
            constraint=models.UniqueConstraint(fields=('date', 'water_source', 'location', 'tank', 'shift'), name='unique_water_tank_reading_per_shift'),
        ),
    ]
