# Generated by Django 6.1.1 on 2026-10-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('laundry_in_date', models.DateField()),
                ('laundry_in_shift', models.CharField(max_length=50)),
                ('laundry_in_charge', models.CharField(max_length=150)),
                ('laba_date', models.DateField(blank=True, null=True)),
                ('laba_shift', models.CharField(blank=True, default='', max_length=50)),
                ('laba_in_charge', models.CharField(blank=True, default='', max_length=150)),
                ('banlaw_date', models.DateField(blank=True, null=True)),
                ('banlaw_shift', models.CharField(blank=True, default='', max_length=50)),
                ('banlaw_in_charge', models.CharField(blank=True, default='', max_length=150)),
                ('sampay_date', models.DateField(blank=True, null=True)),
                ('sampay_shift', models.CharField(blank=True, default='', max_length=50)),
                ('sampay_in_charge', models.CharField(blank=True, default='', max_length=150)),
                ('pinaw_date', models.DateField(blank=True, null=True)),
                ('pinaw_shift', models.CharField(blank=True, default='', max_length=50)),
                ('pinaw_in_charge', models.CharField(blank=True, default='', max_length=150)),
                ('tiklop_date', models.DateField(blank=True, null=True)),
                ('tiklop_shift', models.CharField(blank=True, default='', max_length=50)),
                ('tiklop_in_charge', models.CharField(blank=True, default='', max_length=150)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('returned_by', models.CharField(blank=True, default='', max_length=150)),
                ('encoded_by', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('LAUNDRY_IN', 'Laundry IN'), ('FOR_LABA', 'For Laba'), ('LABA', 'Laba (Washing)'), ('FOR_BANLAW', 'For Banlaw'), ('BANLAW', 'Banlaw (Rinsing)'), ('FOR_SAMPAY', 'For Sampay'), ('SAMPAY', 'Sampay (Hanging)'), ('FOR_PINAW', 'For Pinaw'), ('PINAW', 'Pinaw (Ironing)'), ('FOR_TIKLOP', 'For Tiklop'), ('TIKLOP', 'Tiklop (Folding)'), ('READY_FOR_RETURN', 'Ready for Return'), ('RETURNED', 'Returned')], default='FOR_LABA', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_records', to='core.location')),
            ],
            options={
                'ordering': ['-laundry_in_date', '-id'],
            },
        ),
    ]
