# Generated by Django 6.1.1 on 2026-10-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrecord',
            name='banlaw_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='laba_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='laundry_in_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='pinaw_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='returned_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='sampay_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryrecord',
            name='tiklop_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
