# Generated by Django 6.1.1 on 2026-10-07 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_laundryrecord_banlaw_time_laundryrecord_laba_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrecord',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='item',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LaundryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laundry.laundryrecord')),
            ],
        ),
    ]
