# Generated by Django 6.1.1 on 2026-10-07 00:21

from django.db import migrations


def migrate_laundry_items(apps, schema_editor):
    LaundryRecord = apps.get_model('laundry', 'LaundryRecord')
    LaundryRecordItem = apps.get_model('laundry', 'LaundryRecordItem')
    for record in LaundryRecord.objects.all():
        if record.item and record.quantity:
            LaundryRecordItem.objects.create(
                laundry_record=record,
                item_description=record.item,
                quantity=record.quantity,
                unit='pcs'
            )
            record.total_quantity = record.quantity
            record.save(update_fields=['total_quantity'])

def reverse_migrate_laundry_items(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_laundryrecord_total_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_laundry_items, reverse_migrate_laundry_items)
    ]
