# Generated by Django 6.1.1 on 2026-10-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_auto_20261007_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryrecord',
            name='item',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: Use LaundryRecordItem instead.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='DEPRECATED: Use LaundryRecordItem instead.', null=True),
        ),
    ]
