# Generated by Django 6.1.1 on 2026-10-07 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting'),
        ('laundry', '0005_alter_laundryrecord_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrecorditem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_items', to='core.location'),
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_records', to='core.location'),
        ),
    ]
