# Generated by Django 6.1.1 on 2026-10-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casket_id', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=150)),
                ('casket_type', models.CharField(max_length=100)),
                ('size', models.CharField(default='Standard Adult', max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=150)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('NEEDS_REPAIR', 'Needs Repair'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('USED', 'Used'), ('FOR_REPAIR', 'For Repair'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=20)),
                ('date_received', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['casket_id'],
            },
        ),
        migrations.CreateModel(
            name='CasketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RECEIVE', 'Receive Stock'), ('RESERVE', 'Reserve'), ('UNRESERVE', 'Cancel Reservation'), ('SELL', 'Sell'), ('USE', 'Use in Service'), ('MARK_FOR_REPAIR', 'Mark for Repair'), ('REPAIR_COMPLETE', 'Repair Complete'), ('TRANSFER', 'Transfer Location')], max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('deceased_name', models.CharField(blank=True, default='', max_length=200)),
                ('contract_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
