# Generated by Django 6.1.1 on 2026-10-04 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caskets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casket',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caskets', to='core.location'),
        ),
        migrations.AddField(
            model_name='caskettransaction',
            name='casket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='caskets.casket'),
        ),
        migrations.AddField(
            model_name='caskettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
