# Generated by Django 6.1.1 on 2026-10-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caskets', '0002_initial'),
        ('core', '0003_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('relationship_to_deceased', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=20)),
                ('funeral_case_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Chapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('capacity', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied / Lamay'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapel_units', to='core.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CasketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=50, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lamay_start_date', models.DateField(blank=True, null=True)),
                ('lamay_start_time', models.TimeField(blank=True, null=True)),
                ('expected_burial_date', models.DateField(blank=True, null=True)),
                ('burial_time', models.TimeField(blank=True, null=True)),
                ('service_status', models.CharField(default='ACTIVE_LAMAY', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casket_sales', to='caskets.buyer')),
                ('casket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='caskets.casket')),
                ('encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_sales', to=settings.AUTH_USER_MODEL)),
                ('chapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casket_sales', to='caskets.chapel')),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casket_sales', to='caskets.deceased')),
            ],
            options={
                'ordering': ['-date_sold'],
            },
        ),
        migrations.CreateModel(
            name='LamayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamay_id', models.CharField(max_length=50, unique=True)),
                ('funeral_case_id', models.CharField(blank=True, default='', max_length=100)),
                ('lamay_start_date', models.DateField()),
                ('lamay_start_time', models.TimeField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('expected_burial_date', models.DateField(blank=True, null=True)),
                ('burial_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('PREPARING', 'Preparing'), ('ACTIVE', 'Active / Lamay'), ('FOR_BURIAL', 'For Burial'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lamay_records', to='caskets.buyer')),
                ('casket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamay_records', to='caskets.casket')),
                ('casket_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamay_records', to='caskets.casketsale')),
                ('chapel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lamay_records', to='caskets.chapel')),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lamay_records', to='caskets.deceased')),
                ('encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_lamays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lamay_start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapelTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(blank=True, default='', max_length=200)),
                ('casket_removed', models.BooleanField(default=False)),
                ('chairs_arranged', models.BooleanField(default=False)),
                ('tables_cleaned', models.BooleanField(default=False)),
                ('floor_cleaned', models.BooleanField(default=False)),
                ('bathroom_checked', models.BooleanField(default=False)),
                ('trash_removed', models.BooleanField(default=False)),
                ('equipment_checked', models.BooleanField(default=False)),
                ('inventory_checked', models.BooleanField(default=False)),
                ('chapel_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='caskets.chapel')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_turnovers', to=settings.AUTH_USER_MODEL)),
                ('lamay_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnovers', to='caskets.lamayrecord')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
