# Generated by Django 6.1.1 on 2026-10-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caskets', '0003_buyer_deceased_chapel_casketsale_lamayrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casketsale',
            name='is_residence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casketsale',
            name='residence_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='is_residence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='residence_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lamayrecord',
            name='chapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamay_records', to='caskets.chapel'),
        ),
    ]
