# Generated by Django 6.1.1 on 2026-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caskets', '0004_casketsale_is_residence_casketsale_residence_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='deceased',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='relationship_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deceased',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deceased',
            name='cause_of_death',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='deceased',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deceased',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deceased',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deceased',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deceased',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='assigned_staff',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='wake_location',
            field=models.CharField(choices=[('ALAALA', 'Alaala Funeral Homes'), ('RESIDENCE', 'Client Residence'), ('CHURCH', 'Church'), ('CEMETERY', 'Cemetery'), ('OTHER', 'Other')], default='ALAALA', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='lamayrecord',
            name='status',
            field=models.CharField(choices=[('ARRANGEMENT', 'Arrangement'), ('RESERVED', 'Reserved'), ('PREPARING', 'Preparing'), ('ACTIVE', 'Active Wake'), ('READY_FOR_BURIAL', 'Ready for Burial'), ('FOR_BURIAL', 'For Burial'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=30),
        ),
    ]
