# Generated by Django 6.1.1 on 2026-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caskets', '0005_alter_buyer_options_alter_deceased_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamayrecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='expected_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lamayrecord',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
