# Generated by Django 6.1.1 on 2026-10-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caskets', '0006_lamayrecord_discount_lamayrecord_expected_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapel',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
