# Generated by Django 6.1.1 on 2026-10-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Water', 'Water'), ('Air Conditioning', 'Air Conditioning'), ('Lighting', 'Lighting'), ('Furniture', 'Furniture'), ('Doors/Locks', 'Doors/Locks'), ('Ceiling/Roof', 'Ceiling/Roof'), ('Walls/Paint', 'Walls/Paint'), ('Bathroom', 'Bathroom'), ('Cleaning', 'Cleaning'), ('Equipment', 'Equipment'), ('Other', 'Other')], max_length=50)),
                ('issue', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('reported_by', models.CharField(max_length=150)),
                ('date_reported', models.DateField()),
                ('assigned_to', models.CharField(blank=True, default='', max_length=150)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.FileField(blank=True, null=True, upload_to='maintenance/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='core.location')),
            ],
            options={
                'ordering': ['-date_reported', '-id'],
            },
        ),
    ]
