# Generated by Django 6.1.1 on 2026-10-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PENDING', 'Pending'), ('FOR_REPAIR', 'For Repair'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20),
        ),
    ]
