# Generated by Django 6.1.1 on 2026-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff_members', to='core.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, default='8am to 5pm', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
